/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowajouter_reclamation (void);
GtkWidget* create_windowafficher_reclamation (void);
GtkWidget* create_windowserviceleplusreclame (void);
